source 'https://github.com/CocoaPods/Specs'

platform :ios, '8.0'
use_frameworks!

def sharedPods
  pod 'RxSwift', '3.4.0'
  pod 'RxCocoa', '3.4.0'
  pod 'Moya/RxSwift', '8.0.3'
  pod 'SwiftyJSON', '3.1.4'
end

def testPods
  pod 'Quick', '1.1.0'
  pod 'Nimble', '6.1.0'
  pod 'RxBlocking', '3.4.0'
end

target 'github' do
  sharedPods
end

target 'githubTests' do
  sharedPods
  testPods
end
